name: AI-Threat-Detection-CrowdStrike-CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly retraining

env:
  AWS_REGION: us-east-1
  ECR_REPO: your-ecr-repo/ai-threat-detection
  FALCON_API_TEST_CREDS: ${{ secrets.FALCON_TEST_CREDS }}

jobs:
  train-models:
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          
      - name: Cache model dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            models/
          key: ${{ runner.os }}-models-${{ hashFiles('requirements.txt') }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt boto3 scikit-learn tensorflow --no-cache-dir
          
      - name: Train Ransomware Model
        run: |
          python src/train_ransomware_model.py \
            --data cic-ids-2017 \
            --output models/ransomware_model.pkl
          
      - name: Train DDoS Model
        run: |
          python src/train_ddos_model.py \
            --data cic-ddos-2019 \
            --output models/ddos_model.pkl
      
      - name: Upload Models
        uses: actions/upload-artifact@v4
        with:
          name: threat-models
          path: |
            models/ransomware_model.pkl
            models/ddos_model.pkl
          retention-days: 7

  test-integration:
    needs: train-models
    runs-on: ubuntu-latest
    services:
      mock-falcon-api:
        image: yourorg/mock-falcon-api:v1
        ports:
          - "8080:8080"
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Models
        uses: actions/download-artifact@v4
        with:
          name: threat-models
          path: models
          
      - name: Run Integration Tests
        env:
          FALCON_BASE_URL: "http://localhost:8080"
        run: |
          pip install pytest pytest-cov
          pytest tests/integration/ \
            --cov=src \
            --cov-report=xml \
            --log-level=DEBUG
          
      - name: Upload Coverage
        uses: codecov/codecov-action@v4

  deploy-to-aws:
    needs: test-integration
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Models
        uses: actions/download-artifact@v4
        with:
          name: threat-models
          path: models
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-action-${{ github.run_id }}
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
          
      - name: Build Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64 \
            -t $ECR_REPO:$GITHUB_SHA \
            --load .
          
      - name: Push to ECR
        run: |
          docker push $ECR_REPO:$GITHUB_SHA
          
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name CrowdStrikeAIDetector \
            --image-uri $ECR_REPO:$GITHUB_SHA \
            --region $AWS_REGION

  falcon-api-validation:
    needs: deploy-to-aws
    runs-on: ubuntu-latest
    steps:
      - name: Test Live Falcon API
        uses: fjogeleit/http-request-action@v2
        with:
          url: "https://api.crowdstrike.com/detects?filter=ai_model:true"
          method: GET
          customHeaders: '{"Authorization": "Bearer ${{ secrets.FALCON_API_KEY }}"}'
          timeout: 10000
          retryOnError: true
          retryDelay: 5000
          maxRetries: 3
